spring:
  application:
    name: batch-demo
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: ${ORACLE_DRIVER}
    url: ${ORACLE_DB_URL}
    username: ${ORACLE_DB_USER}
    password: ${ORACLE_DB_PASS}
    hikari:
      pool-name: BatchDemoHikariPool
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 60000
      max-lifetime: 1800000
      auto-commit: false
      connection-test-query: SELECT 1